name: Sync Fork (On Demand)

# on:
#   workflow_dispatch:
on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # No change needed here, v3 already supports Node.js 20

      - name: Configure git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "noreply@your-email.com"

      - name: Add upstream remote (if not already added)
        run: |
          if [ ! -z "$(git remote -v | grep upstream)" ]; then
            echo "Upstream remote already exists."
          else
            git remote add upstream https://github.com/coolnerdycoder/cooliptv-tataplay.m3u.git
          fi

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Check for new commits (optional)
        id: check-changes
        run: |
          upstream_commit_sha=$(git rev-parse upstream/main)
          head_commit_sha=$(git rev-parse HEAD)
          if [ "$upstream_commit_sha" != "$head_commit_sha" ]; then
            echo "There are new commits in the upstream repository."
          else
            echo "Your fork is already up-to-date."
          fi

      - name: Merge upstream changes (optional, based on check-changes output)
        if: steps.check-changes.outputs.new_commits == 'true'
        run: |
          git checkout main
          git merge upstream/main
          git push origin main
